[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "evoker"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = "../VERSION"}
description = "Evoker worker runtime"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
evoker = ["pythons/**/*"]
