[tox]
envlist = py310, py311, py312, py313
isolated_build = True

[testenv]
deps =
    pytest
    hypothesis
    pytest-xprocess
    pyarrow

commands =
    pip install ../../evoker
    pytest tests/
